if (typeof window === "undefined") {
  /**
   * Settings exposed to the server.
   */
  module.exports = {
    BOILERPLATE_AUTH0_CLIENT_ID: process.env.BOILERPLATE_AUTH0_CLIENT_ID,
    BOILERPLATE_AUTH0_CLIENT_SECRET:
      process.env.BOILERPLATE_AUTH0_CLIENT_SECRET,
    BOILERPLATE_AUTH0_SCOPE: process.env.BOILERPLATE_AUTH0_SCOPE,
    BOILERPLATE_AUTH0_DOMAIN: process.env.BOILERPLATE_AUTH0_DOMAIN,
    REDIRECT_URI: process.env.REDIRECT_URI,
    POST_LOGOUT_REDIRECT_URI: process.env.POST_LOGOUT_REDIRECT_URI,
    SESSION_COOKIE_SECRET: process.env.BOILERPLATE_SESSION_COOKIE_SECRET,
    SESSION_COOKIE_LIFETIME: process.env.SESSION_COOKIE_LIFETIME
  };
} else {
  /**
   * Settings exposed to the client.
   */
  module.exports = {
    BOILERPLATE_AUTH0_CLIENT_ID: process.env.BOILERPLATE_AUTH0_CLIENT_ID,
    BOILERPLATE_AUTH0_SCOPE: process.env.BOILERPLATE_AUTH0_SCOPE,
    BOILERPLATE_AUTH0_DOMAIN: process.env.BOILERPLATE_AUTH0_DOMAIN,
    REDIRECT_URI: process.env.REDIRECT_URI,
    POST_LOGOUT_REDIRECT_URI: process.env.POST_LOGOUT_REDIRECT_URI
  };
}
